# =============================================
# TRIBU E-COMMERCE — CONFIGURACIÓN DE PRODUCCIÓN
# =============================================

# BASE DE DATOS
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/tribu_db?useSSL=false&serverTimezone=America/Bogota}
spring.datasource.username=${DB_USERNAME:tribu_app_user}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# HIBERNATE/JPA (Seguridad ante todo, NUNCA UPDATE en PRD sin supervisión)
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# SERVIDOR
server.port=8080

# JWT
# Configurado por variables de entorno
jwt.secret=${JWT_SECRET:7xVUR3ikA6OeM75Hds07urEBieVmi4EzmdlHOKtjjKydimiXwwDOKlgYfKEvhJm20bXQo2X9h8cA4MaHnFxfRQ==}
jwt.expiration=86400000

# CORREO (SMTP Seguro)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:admin@tribu.com}
spring.mail.password=${MAIL_PASSWORD:aqui-tu-app-password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ARCHIVOS (Ajustes de memoria para producción)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
app.upload.dir=./uploads

# NOTIFICACIONES WEB PUSH
vapid.public.key=${VAPID_PUBLIC_KEY:BEHFUbjQ2zV3d35OlNb3QvbUMQhwLN5sDtL7BLLBYQlzbRSN0-k2a84nemEO8R6w4Oudhj0-qPhqDTP3qct_qG8}
vapid.private.key=${VAPID_PRIVATE_KEY:KvSXC2LOpt4MsfC_nEEtc5ZErXwwETBAjmDND6AeITY}
vapid.subject=mailto:admin@tudominio.com

# TELEGRAM BOT (Asumido por variables)
telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.bot.username=${TELEGRAM_BOT_USERNAME:TribuCardAdminBot}
telegram.bot.admin.chat.ids=${TELEGRAM_ADMIN_CHAT_IDS}

# LOGGING
logging.level.org.springframework=WARN
logging.level.com.tribu=INFO
